name: SQL Lint

on:
  push:
    paths:
      - '**/*.sql'
  pull_request:
    paths:
      - '**/*.sql'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install sqlfluff (with Jinja)
        run: pip install "sqlfluff[jinja]"
      - name: Lint SQL
        run: sqlfluff lint .
